/** Figma Node 20:1398 (Main_Default_Desktop_1920~1080) 디자인 토큰 */
export const figma = {
  colors: {
    primary: "#00376e",
    primaryLight: "#e5edff",
    yellow: "#ffe02f",
    page: "#fafafa",
    white: "#ffffff",
    text: "#010101",
    textBody: "#1d1d1d",
    textSub: "#3d3d3d",
    textMuted: "#656565",
    textPlaceholder: "#919191",
    border: "#e0e0e0",
    dotInactive: "#e4e4e4",
  },
  layout: {
    container: 1200,
    gnbHeight: 86,
    gnbLogoWidth: 200,
    gnbLogoHeight: 46,
    infoBarHeight: 72,
    heroBannerWidth: 791,
    heroLoginWidth: 383,
    heroHeight: 320,
    heroGap: 26,
    heroLoginPadding: 28,
    infoCardHeight: 200,
    infoCardWide: 588,
    infoCardNarrow: 282,
    infoCardGap: 24,
    courseTitleWidth: 180,
    courseCardWidth: 282,
    courseCardHeight: 298,
    courseImageHeight: 188,
    courseCardGap: 24,
    courseScrollWidth: 996,
    categoryCardWidth: 78,
    categoryIconSize: 68,
    bannerHeight: 240,
    bannerTextOffset: 100,
    buttonHeight: 54,
    reviewCardWidth: 281,
    reviewCardHeight: 198,
    reviewScrollWidth: 994,
    noticePanelWidth: 588,
    footerHeight: 314,
    floatingBannerWidth: 130,
    floatingBannerHeight: 224,
    topButtonSize: 50,
  },
  radius: {
    card: 10,
    image: 8,
    button: 6,
    search: 4,
    top: 8,
    pill: 999,
    dotActive: 5,
  },
  spacing: {
    heroSection: 36,
    infoSection: 30,
    categorySectionTop: 20,
    categorySectionBottom: 36,
    courseSection: 48,
    bannerSection: 28,
    packageSection: 100,
    reviewSection: 100,
    noticeSection: 56,
  },
  typography: {
    infoBar: "text-[20px] font-semibold leading-none",
    nav: "text-[15px] font-medium leading-[22px]",
    utility: "text-[14px] font-semibold leading-none",
    searchPlaceholder: "text-[14px] font-medium",
    sectionTitle: "text-[24px] font-bold leading-[34px]",
    heroWelcome: "text-[24px] font-medium leading-[1.35]",
    cardTitle: "text-[20px] font-bold leading-snug",
    phoneLabel: "text-[14px] font-medium leading-none",
    phoneTitle: "text-[20px] font-bold leading-none",
    phoneNumber: "text-[32px] font-bold leading-none",
    phoneHours: "text-[13px] font-medium leading-[1.4]",
    categoryLabel: "text-[12px] font-medium leading-tight",
    courseCardTitle: "text-[16px] font-bold leading-snug",
    bannerTitle: "text-[32px] font-bold leading-[1.35]",
    bannerSubtitle: "text-[16px] font-medium leading-none",
    nationalButton: "text-[18px] font-bold leading-none",
    reviewMore: "text-[16px] font-medium leading-none",
    floatingText: "text-[18px] font-bold leading-[1.35]",
    topLabel: "text-[14px] font-semibold leading-none",
  },
  shadow: {
    topButton: "0 2px 8px rgba(0, 0, 0, 0.08)",
  },
} as const;

export const homeColors = {
  navy: figma.colors.primary,
  navyDark: figma.colors.primary,
  blueLight: figma.colors.primaryLight,
  yellow: figma.colors.yellow,
  grayBg: figma.colors.page,
  grayBorder: figma.colors.border,
  grayText: figma.colors.textMuted,
  darkText: figma.colors.textBody,
  footerDark: "#1d2b38",
} as const;

/** Tailwind class helpers derived from Figma fills */
export const figmaClass = {
  pageBg: "bg-[#fafafa]",
  primaryBg: "bg-[#00376e]",
  primaryLightBg: "bg-[#e5edff]",
  whiteBg: "bg-white",
  textPrimary: "text-[#010101]",
  textBody: "text-[#1d1d1d]",
  textSub: "text-[#3d3d3d]",
  textMuted: "text-[#656565]",
  textPlaceholder: "text-[#919191]",
  borderDefault: "border-[#e0e0e0]",
  roundedCard: "rounded-[10px]",
  roundedImage: "rounded-[8px]",
  roundedButton: "rounded-[6px]",
} as const;
